 installing numpy

importing numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
c = a + b
print(c)

[11 22 33 44 55]


In [4]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[10, 20, 30], [40, 50, 60]])
C = A + B
print(C)

[[11 22 33]
 [44 55 66]]


In [5]:
a[2:]

array([3, 4, 5])

In [6]:
a.ndim

1

In [7]:
A.ndim

2

In [8]:
print("No of dimensions in a:", A.ndim)
print("Shape of a:", A.shape)
print("Size of a:", A.size)
print("Data type of a:", A.dtype)
print("len of shape of a:", len(A.shape))

No of dimensions in a: 2
Shape of a: (2, 3)
Size of a: 6
Data type of a: int64
len of shape of a: 2


In [9]:
A.ndim == len(A.shape)

True

In [10]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [15]:
three_d_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("Dimensions : ",three_d_array.ndim)
print("Shape : ",three_d_array.shape)
print("Size : ",three_d_array.size)

Dimensions :  3
Shape :  (2, 2, 3)
Size :  12


In [16]:
three_d_array = np.array([[[1,2,3],
                           [4,5,6]],
                           [[7,8,9],
                            [10,11,12]]])
print("Dimensions : ",three_d_array.ndim)
print("Shape : ",three_d_array.shape)
print("Size : ",three_d_array.size)

Dimensions :  3
Shape :  (2, 2, 3)
Size :  12


In [18]:
four_d_array = np.array([[
                        [[1, 2, 1],
                        [3, 4, 1]], 

                        [[5, 6, 2], 
                        [7, 8, 2]]],

                        [[[9, 10, 3], 
                        [11, 12, 3]], 

                        [[13, 14, 4],
                        [15, 16, 4]]
                        ]])
print("Dimensions : ",four_d_array.ndim)
print("Shape : ",four_d_array.shape)
print("Size : ",four_d_array.size)

Dimensions :  4
Shape :  (2, 2, 2, 3)
Size :  24


In [19]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.empty(3)

array([7.74860419e-304, 7.74860419e-304, 7.74860419e-304])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2,9,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5])

In [23]:
np.linspace(2,5,50)

array([2.        , 2.06122449, 2.12244898, 2.18367347, 2.24489796,
       2.30612245, 2.36734694, 2.42857143, 2.48979592, 2.55102041,
       2.6122449 , 2.67346939, 2.73469388, 2.79591837, 2.85714286,
       2.91836735, 2.97959184, 3.04081633, 3.10204082, 3.16326531,
       3.2244898 , 3.28571429, 3.34693878, 3.40816327, 3.46938776,
       3.53061224, 3.59183673, 3.65306122, 3.71428571, 3.7755102 ,
       3.83673469, 3.89795918, 3.95918367, 4.02040816, 4.08163265,
       4.14285714, 4.20408163, 4.26530612, 4.32653061, 4.3877551 ,
       4.44897959, 4.51020408, 4.57142857, 4.63265306, 4.69387755,
       4.75510204, 4.81632653, 4.87755102, 4.93877551, 5.        ])

In [24]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

axis = 0 means column wise elements will be sorted
axis = 1 means rows wise elements will be sorted

In [29]:
arr = np.array([[14, 21, 13], [42, 15, 46], [27, 83, 92]])
arr_sorted_1 = np.sort(arr, axis=1)
arr_sorted_0 = np.sort(arr, axis=0)
#print(arr_sorted_1)
print("Original array:\n", arr)
print("Sorted array along rows:\n", arr_sorted_1)
print("Sorted array along columns:\n", arr_sorted_0)

Original array:
 [[14 21 13]
 [42 15 46]
 [27 83 92]]
Sorted array along rows:
 [[13 14 21]
 [15 42 46]
 [27 83 92]]
Sorted array along columns:
 [[14 15 13]
 [27 21 46]
 [42 83 92]]


# The numpy.argsort() function performs an indirect sort on a NumPy array, returning an array of indices that would put the original array's elements into ascending order. It does not modify the original array. 


In [30]:
print("argsort along rows:\n", np.argsort(arr, axis=1))
print("argsort along columns:\n", np.argsort(arr, axis=0))


argsort along rows:
 [[2 0 1]
 [1 0 2]
 [0 1 2]]
argsort along columns:
 [[0 1 0]
 [2 0 1]
 [1 2 2]]


In [31]:
print("original array:\n", arr)
print("lexsort along rows:\n", np.lexsort(arr.T))
print("lexsort along columns:\n", np.lexsort(arr))
print("searchsorted along rows:\n", np.searchsorted(arr[0], 15))
print("searchsorted along columns:\n", np.searchsorted(arr[:,0], 30))
print("partition along rows:\n", np.partition(arr, 1, axis=1))
print("partition along columns:\n", np.partition(arr, 1, axis=0))

original array:
 [[14 21 13]
 [42 15 46]
 [27 83 92]]
lexsort along rows:
 [0 1 2]
lexsort along columns:
 [0 1 2]
searchsorted along rows:
 1
searchsorted along columns:
 1
partition along rows:
 [[13 14 21]
 [15 42 46]
 [27 83 92]]
partition along columns:
 [[14 15 13]
 [27 21 46]
 [42 83 92]]


In [32]:
arr1 = np.array([3, 1, 2])
arr2 = np.array([6, 4, 5])
print("Original arrays:\n", arr1, arr2)
print("Concatenated array:\n", np.concatenate((arr1, arr2)))
print("Stacked array along axis 0:\n", np.stack((arr1, arr2), axis=0))
print("Stacked array along axis 1:\n", np.stack((arr1, arr2), axis=1))

Original arrays:
 [3 1 2] [6 4 5]
Concatenated array:
 [3 1 2 6 4 5]
Stacked array along axis 0:
 [[3 1 2]
 [6 4 5]]
Stacked array along axis 1:
 [[3 6]
 [1 4]
 [2 5]]


In [35]:
# reshape
arr = np.arange(12)
print("Original array:\n", arr)
reshaped_arr = arr.reshape((2, 6))
print("Reshaped array (2x6):\n", reshaped_arr)

Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [36]:
array = np.arange(8)
a1 = array[np.newaxis, :]
a2 = array[:, np.newaxis]
print("Original array shape:", array.shape)
print("After adding new axis at position 0:", a1.shape)
print("After adding new axis at position 1:", a2.shape)
print("Original array:\n", array)
print("After adding new axis at position 0:\n", a1)
print("After adding new axis at position 1:\n", a2)

Original array shape: (8,)
After adding new axis at position 0: (1, 8)
After adding new axis at position 1: (8, 1)
Original array:
 [0 1 2 3 4 5 6 7]
After adding new axis at position 0:
 [[0 1 2 3 4 5 6 7]]
After adding new axis at position 1:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [38]:
b1 = np.expand_dims(array, axis=0)
b2 = np.expand_dims(array, axis=1)
print("Using expand_dims - shape after adding new axis at position 0:", b1.shape)
print("Using expand_dims - shape after adding new axis at position 1:", b2.shape)
print("original array:\n", array)
print("Using expand_dims - after adding new axis at position 0:\n", b1)
print("Using expand_dims - after adding new axis at position 1:\n", b2)

Using expand_dims - shape after adding new axis at position 0: (1, 8)
Using expand_dims - shape after adding new axis at position 1: (8, 1)
original array:
 [0 1 2 3 4 5 6 7]
Using expand_dims - after adding new axis at position 0:
 [[0 1 2 3 4 5 6 7]]
Using expand_dims - after adding new axis at position 1:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
a[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
print(a[a<2])

[1]


In [42]:
a<2

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [43]:
b=np.nonzero(a<5)
print("Indices of elements less than 5:", b)

Indices of elements less than 5: (array([0, 0, 0, 1]), array([0, 1, 2, 0]))


In [45]:
a = np.arange(1,31).reshape((2, 15))
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [46]:
v = np.hsplit(a, 3)
v

[array([[ 1,  2,  3,  4,  5],
        [16, 17, 18, 19, 20]]),
 array([[ 6,  7,  8,  9, 10],
        [21, 22, 23, 24, 25]]),
 array([[11, 12, 13, 14, 15],
        [26, 27, 28, 29, 30]])]